### ISSUE TITLE
debride 1.0.0 doesn't enforce sexp_processor >= 4.5.0, results in undefined method `expand_dirs_to_files'

### ISSUE THREAD

**Issue by jrafanie** [seattlerb/debride#1]
Thanks for writing this.  More static analysis is a welcome addition.

In case others run into this.

I get this with sexp_processor 4.4.5.  gem install sexp_processor ~>4.5.0 fixes it:
```
$ debride lib
.gem/ruby/2.1.5/gems/debride-1.0.0/lib/debride.rb:24:in `run': undefined method `expand_dirs_to_files' for Debride:Class (NoMethodError)
	from .gem/ruby/2.1.5/gems/debride-1.0.0/bin/debride:5:in `<top (required)>'
	from .gem/ruby/2.1.5/bin/debride:23:in `load'
	from .gem/ruby/2.1.5/bin/debride:23:in `<main>'
```

It looks like this method was added in [sexp_processor 4.5.0](https://github.com/seattlerb/sexp_processor/blob/5b5742753b7c1297172be1105f82c99a25e3ae71/History.txt#L5)

I wasn't sure if there was a reason to not list this in a gemspec dependency or if this should go in the README.

Thanks again!

**Comment by zenspider** [comment]
Yup. Known issue

**Comment by jrafanie** [comment]
Great!  Thanks! :star:
