### ISSUE TITLE
Allow debride to scan everything, but only report for a subset (file or dir)

### ISSUE THREAD

**Issue by phiggins** [seattlerb/debride#17]
It would be nice to be able to focus the scope of debride. The use case I have in mind for this is if I'm looking at some particularly gross class and want to refactor it, I might use debride to see if it has any dead code I can remove first.

I think a command line flag for this would make sense. To only check for dead code in a specific file but look for method calls in the `lib` and `config` directories, I could do something like:

```
debride --focus=lib/my_library/some_class.rb lib/ config/
```

**Comment by zenspider** [comment]
I think this title is misleading. You don't care how I do it. You just want to change what is reported. No?

**Comment by phiggins** [comment]
> I think this title is misleading. You don't care how I do it. You just want to change what is reported. No?

Yes, you're right.

**Comment by zenspider** [comment]
Better title?

**Comment by zenspider** [comment]
I think this will require an extra map from defn -> file, but should otherwise be doable.

**Comment by phiggins** [comment]
I'd `s/file/subset/`, but yes it is better.

**Comment by zenspider** [comment]
Do you want to be able to pass a comma delimited list of files? or?

**Comment by phiggins** [comment]
I was thinking more like a file or directory.

**Comment by zenspider** [comment]
Done! Easier than I thought it would be.

**Comment by phiggins** [comment]
Nice! I'll try it out when I get a chance.
