### ISSUE TITLE
class method 'inherited' reported, even if it would be called

### ISSUE THREAD

**Issue by recursive-madman** [seattlerb/debride#21]
Given this input file:
```ruby
class A
  def self.inherited(base)
    puts "#{base.name} inherits from #{name}"
  end
end

class B < A
end
```

it can be verified, that the `inherited` method is actually called (as expected):
```sh
$ ruby try-inherit.rb 
B inherits from A
```

however, debride complains about it:
```sh
$ debride try-inherit.rb
These methods MIGHT not be called:

A
  inherited                           try-inherit.rb:2
```

**Comment by zenspider** [comment]
Yup. That's how debride works. You didn't analyze any code that calls that method, so it reports it as potentially dead. Add it to a whitelist to remove it from the report.
