### ISSUE TITLE
debride_rm doesn't actually work

### ISSUE THREAD

**Issue by dacook** [seattlerb/debride#45]
I might be missing something obvious, but this doesn't work for me. 

The debride output is in a format like this:
```
   method_name                    ./file/name.rb:203-207
```

But the `debride_rm` script seems to be expecting a single line only, and reports everything as 'unparsed'.

**Comment by dacook** [comment]
We might just need to change a few lines here to parse the line range and add each line to the array.
https://github.com/seattlerb/debride/blob/5078ab0c71ccd5f043f74cfa356cc8376079eb36/bin/debride_rm#L55-L58

However I don't have time right now to try it.

**Comment by zenspider** [comment]
If you're insane enough to do this... send me a PR

**Comment by zenspider** [comment]
I'm starting to poke at this... not sure if I'm going to just patch this sketchy script or do a full revamp.

I kinda want to teach it VC or provide some option for a command string to run between changes so it can commit each removal.

**Comment by zenspider** [comment]
This works now. Release coming soonish.
