### ISSUE TITLE
Look at Rails callbacks to detect method usage

### ISSUE THREAD

**Issue by tristil** [seattlerb/debride#5]
If debride looked at `before_create :something`, etc. that would whitelist a lot of false positive methods in a Rails project.

**Comment by zenspider** [comment]
Wanna try it out and show me the before / after?

**Comment by zenspider** [comment]
The thing I'm worried about with just taking all symbols as potential method calls is that it will lead to false negatives. That's why I'm toying with the idea of a logging send wrapper instead.

Always open to experimentation tho.

**Comment by tristil** [comment]
Well I really just meant hardcoding some of the Rails convention stuff, like hooks on AR models, before filters on controllers, and maybe reading routes to the find methods on controllers. But actually just exercising the code and seeing where things go is obviously a more robust solution (I also could see it being annoying to have to maintain the gem to keep up with Rails and other frameworks). The question is how to exercise the code. Maybe use a project's test suite like this blog post? http://tenderlovemaking.com/2015/02/13/predicting-test-failues.html

As for a before and after, I can just see that the methods for say a `User` model are all things like `valid_tos?` that are used in `validate` declarations and thus never called directly.

**Comment by zenspider** [comment]
So, as a thought experiment, I ran debride over seattlerb.org's code. In order to do that, I needed to make debride work on erb (release coming soon) and I needed to whitelist some stuff. I did that with:

```
% rake routes | grep "#" | cut -f 2 -d\# | sort -u > whitelist.txt
```

That got me a fair way through the list, tho it has the same problem as your suggestion of analyzing through the tests, namely that you have false positives. Just because something is wired up to the routes or tested in the tests doesn't mean that it is actually called anywhere else.

**Comment by tristil** [comment]
Have you seen this? https://github.com/amatsuda/traceroute 

I think it's one thing to make sure that every route matches an action, and every (public) method matches a route, but beyond that I don't know that there could be any way of second-guessing the routes file beyond that. As for using the test suite, I agree that unit tests aren't helpful but using acceptance tests to whitelist things would be, assuming they're properly written.

**Comment by ianlotinsky** [comment]
Going to take traceroute out for a test drive as well.

With regard to handling symbol representations of methods: what do you think of debride specifically identifying Rails model callbacks, model validations, and controller filters and not just symbols in general?

**Comment by zenspider** [comment]
There is still the problem that just because it is tested doesn't mean it is valid, live code. It doesn't matter HOW you go about finding it, either statically or via traceroute... it can be a false positive if there is a test for it but it isn't actually used by anything.

**Comment by tristil** [comment]
But I think if you have a route, a controller, an action, and a view, that's functioning code as far as any automated tool can tell. I think that's just the end of the road. The only thing I could think of that would go further would be to look at server logs or something, but even that would be misleading, because unused != unwanted.

**Comment by zenspider** [comment]
I disagree. For example, I just found an endpoint in seattlerb.org. It had a controller (shared with other live code), an action, a view, and tests... and absolutely NOTHING pointing at it. Debride was able to point this out once I removed the routes from my generated whitelist.

**Comment by tristil** [comment]
I'm confused. What do you mean nothing was pointing at it? No other links?

**Comment by zenspider** [comment]
exactly. It was completely unexposed to the world. Remove the action, view, and test and it makes no difference to the world (except my sanity).

**Comment by ianlotinsky** [comment]
I didn't find traceroute's findings to be helpful at all. debride already helped me eliminate several unused methods. Thanks, Ryan!

(1) Personally, I would want to exclude my test code at first. After removing unused application methods, I would then run the test suite to reveal now broken and unnecessary tests. (Tests will blow up if they still use methods I just removed.) I might then run debride over the application and test code together to reveal any test suite methods that are unused (test helpers, etc.). Perhaps debride could use a command line argument to exclude user-specified folders from the scan (`test`, `spec`, etc.)?

(2) If debride specifically identified Rails native model callbacks, model validations, and controller filter symbols (not "all symbols as potential method calls"), it would eliminate false positives.

If either of these are appealing, I'm interested in helping.

**Comment by zenspider** [comment]
1. I think that's the perfect way to go about this. I'd totally be open to an `--exclude` patch, tho I'm just running mine with `debride app lib` then `debride app lib test`.

2. Look at the code I currently have guarded by `option[:rails]`. I'm sure there are more to add. Open to a PR for that too (separately).

**Comment by ianlotinsky** [comment]
Okay, I'll get started then.

**Comment by zenspider** [comment]
Let me know if I can help. You might want to look at what @phiggins has submitted.

**Comment by zenspider** [comment]
Specifically #9

**Comment by ianlotinsky** [comment]
Looks like @phiggins beat me to the punch. This is exactly what I was looking for. Thanks for merging it in! And thank you, @phiggins for authoring it.

**Comment by tristil** [comment]
That PR closes this issue IMO. That's what I was getting at.
